# Generated by Django 5.1 on 2024-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('proficiencies', models.JSONField()),
                ('proficiency_choices', models.JSONField()),
                ('saving_throws', models.JSONField()),
            ],
        ),
    ]
