# Generated by Django 5.0.3 on 2024-08-12 17:31

import character_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0002_characters_list_character_char_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_list',
            field=models.ForeignKey(default=character_app.models.get_default_characters_list, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='character_app.characters_list'),
        ),
    ]
