# Generated by Django 5.1 on 2024-08-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0003_alter_character_char_list'),
        ('race_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='race_app.race'),
        ),
    ]
