# Generated by Django 5.1 on 2024-08-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0004_alter_character_race'),
        ('class_app', '0001_initial'),
        ('race_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_with_class', to='class_app.charclass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='character_app.characters_list'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_with_race', to='race_app.race'),
        ),
    ]
